import { lossReport } from "../../capabilities.js";

export function project(engine, manifest) {
  const rules = engine.rules.map((r) => `### ${r.name}\n\n${r.content}`).join("\n\n");
  const skillsInline = engine.skills.map((s) => `### skill: ${s.name}\n\n${s.content}`).join("\n\n");
  const content = [
    `<!-- GENERATED by spec-agent — não edite; rode 'spec-agent sync' -->`,
    `# ${manifest.id} — spec-agent harness (portable)`,
    `## Regras\n${rules}`,
    `## Protocolos de skill (inlined — sem skills nativas neste vendor)\n${skillsInline}`,
  ].join("\n\n");
  return { files: [{ path: "AGENTS.md", content }], skills: [], loss: lossReport("agents-md") };
}
