import { lossReport } from "../../capabilities.js";

export function project(engine, manifest) {
  const rulesText = engine.rules.map((r) => `### ${r.name}\n\n${r.content}`).join("\n\n");
  const loss = lossReport("claude");
  const content = [
    `<!-- GENERATED by spec-agent — não edite; rode 'spec-agent sync' -->`,
    `# ${manifest.id} — spec-agent harness (Claude Code)`,
    ``,
    `Projeto: **${manifest.id}**. Engine governado (council, context-economy, project-learning, skill-forge).`,
    ``,
    `## Regras do engine`,
    rulesText,
    ``,
    `## Skills do engine`,
    `Instaladas em \`.claude/skills/\` (invocáveis): ${engine.skills.map((s) => s.name).join(", ")}.`,
  ].join("\n");
  const files = [{ path: "CLAUDE.md", content }];
  const skills = engine.skills.map((s) => ({ path: `.claude/skills/${s.name}/SKILL.md`, content: s.content }));
  return { files, skills, loss };
}
