import { lossReport } from "../../capabilities.js";

export function project(engine, manifest) {
  const rules = engine.rules.map((r) => `- ${r.name}: ${r.content.split("\n")[1] || ""}`).join("\n");
  const content = [
    `<!-- GENERATED by spec-agent -->`,
    `# ${manifest.id} — spec-agent (Copilot)`,
    `## Regras do engine`,
    rules,
  ].join("\n");
  return { files: [{ path: ".github/copilot-instructions.md", content }], skills: [], loss: lossReport("copilot") };
}
